export const LIVE_URL =
  "https://kerala-bank-demo-700028221444.us-central1.run.app/login";

export const LANGS = [
  { id: "en", label: "EN", dir: "ltr", font: "latin" },
  { id: "hi", label: "हिन्दी", dir: "ltr", font: "deva" },
  { id: "ml", label: "മലയാളം", dir: "ltr", font: "mlym" },
  { id: "ta", label: "தமிழ்", dir: "ltr", font: "taml" },
  { id: "ar", label: "عربي", dir: "rtl", font: "arab" },
];

export const COPY = {
  en: {
    nav: {
      product: "Product",
      how: "How it works",
      lenders: "Lenders",
      security: "Security",
      faq: "FAQ",
      login: "Log in",
      lendersCta: "For lenders",
      talk: "Talk to Dhana",
    },
    hero: {
      h1Before: "Voice AI for",
      h1Accent: "lending.",
      sub: "Built for high-stakes credit conversations where trust actually matters.",
      cta: "Talk to Dhana",
      metricStrong: "5,000+",
      metric: "borrowers served",
      invite: "Click to speak with Dhana",
      mic: "Mic permissions needed",
      initiate: "Initiate Call",
      openLive: "Open live Dhana",
    },
    useCases: [
      { id: "personal", kicker: "Dhana", label: "Personal loan", sub: "Cash for life’s jumps" },
      { id: "home", kicker: "Dhana", label: "Home loan", sub: "Buy, build, renovate" },
      { id: "business", kicker: "Dhana", label: "Business loan", sub: "Working capital" },
      { id: "gold", kicker: "Dhana", label: "Gold loan", sub: "Against jewellery" },
      { id: "unsure", kicker: "Dhana", label: "I’m not sure — just talk", sub: "She’ll figure it out" },
    ],
    call: {
      connecting: "Connecting…",
      listening: "Dhana is listening",
      speaking: "Dhana is speaking",
      muted: "Muted",
      hangup: "Hang up",
      mute: "Mute",
      unmute: "Unmute",
      denied: "Microphone blocked. You can still open the live demo.",
      scripts: {
        personal: [
          { who: "dhana", text: "Hi, I’m Dhana. Personal loan — how much do you need?" },
          { who: "you", text: "About five lakh." },
          { who: "dhana", text: "₹5,00,000. I can compare lenders, or we can run the application on this page. Your call." },
        ],
        home: [
          { who: "dhana", text: "Home loan. Buying, building, or renovating?" },
          { who: "you", text: "Renovating. Around five lakh." },
          { who: "dhana", text: "Got it. I’ll hold amount and purpose, then show clean options. No seventeen-field form." },
        ],
        business: [
          { who: "dhana", text: "Business loan. Working capital, or something else?" },
          { who: "you", text: "Working capital. I can pay about eighteen thousand a month." },
          { who: "dhana", text: "I’ll size it to that EMI and put three illustrative offers on the page." },
        ],
        gold: [
          { who: "dhana", text: "Gold loan. Do you want to talk amount first, or tenure?" },
          { who: "you", text: "Amount. Five lakh if the jewellery covers it." },
          { who: "dhana", text: "We’ll treat that as a ceiling and keep the paperwork off your plate." },
        ],
        unsure: [
          { who: "dhana", text: "That’s fine. Tell me what you need the money for, in your words." },
          { who: "you", text: "I just need about five lakh. Not sure which loan." },
          { who: "dhana", text: "I’ll pick a path with you. Amount first, purpose next, EMI after that." },
        ],
      },
    },
    trusted: "Trusted by teams that already originate in India.",
    partners: [
      "Axis Bank",
      "HDFC Bank",
      "SBI",
      "ICICI Bank",
      "Mahindra Finance",
      "Tata Capital",
    ],
    guided: {
      eyebrow: "Guided origination",
      title: "She doesn’t chat about loans. She runs the application.",
      caption: "Watch the page fill as the conversation happens. This is a scripted walkthrough — offers are illustrative, not live quotes.",
      play: "Play",
      pause: "Pause",
      next: "Next",
      prev: "Back",
      you: "You",
      dhana: "Dhana",
      amountLabel: "Amount",
      purposeLabel: "Purpose",
      emiLabel: "Monthly EMI",
      offersLabel: "Illustrative offers",
      illustrative: "Illustrative — not a live quote",
      closer: "You pick. Dhana already did the messy part.",
      chips: ["Home renovation", "Medical", "Education", "Other"],
      offers: [
        { bank: "HDFC Bank", rate: "10.50%*", emi: "₹10,870", speed: "48 hrs" },
        { bank: "Kotak", rate: "10.75%*", emi: "₹11,020", speed: "Same day" },
        { bank: "Axis", rate: "11.00%*", emi: "₹11,180", speed: "24 hrs" },
      ],
      steps: [
        {
          who: "you",
          text: "I need about ₹5 lakh.",
          action: "amount",
        },
        {
          who: "dhana",
          text: "For what — home, medical, or other?",
          action: "purpose",
        },
        {
          who: "you",
          text: "I can manage ₹18,000 a month.",
          action: "emi",
        },
        {
          who: "dhana",
          text: "Three clean options. Compare rate, EMI, disbursal.",
          action: "offers",
        },
        {
          who: "dhana",
          text: "You pick. Dhana already did the messy part.",
          action: "close",
        },
      ],
    },
    how: {
      eyebrow: "How it works",
      title: "Zero forms. Three steps.",
      steps: [
        { n: "01", title: "Say it", body: "Amount, purpose, what you can pay. Spoken in the language you already use." },
        { n: "02", title: "She compares 50+ lenders", body: "Dhana holds the messy matching. You see a short list, not a portal." },
        { n: "03", title: "You pick / KYC", body: "Choose an offer. Complete KYC when you’re ready — not before you’ve seen the shape of the loan." },
      ],
    },
    lending: {
      eyebrow: "Built for lending",
      title: "Every credit conversation, one relationship manager.",
      items: [
        { t: "Personal", d: "Unsecured, purpose-led, EMI-first." },
        { t: "Home", d: "Purchase, construction, renovation." },
        { t: "Business", d: "Working capital without the branch visit." },
        { t: "LAP", d: "Loan against property, explained out loud." },
        { t: "Vehicle", d: "Car and two-wheeler, including used." },
        { t: "Gold", d: "Against jewellery, tenure in plain speech." },
        { t: "Women", d: "Products built for women borrowers, asked for by name." },
        { t: "Cards", d: "Credit card origination without the 12-pager." },
      ],
    },
    why: {
      eyebrow: "Voice, not branches",
      title: "Why talking beats the queue.",
      items: [
        { t: "No token, no hall", d: "The relationship manager is on the page. She doesn’t close at 4:30." },
        { t: "Paperwork is the enemy", d: "You don’t type seventeen fields to find out you don’t qualify. You speak. She fills." },
        { t: "Language is the product", d: "Malayalam, Hindi, Tamil, English, Arabic. Not a subtitle after the English script." },
      ],
    },
    security: {
      eyebrow: "Regulated industries",
      title: "Credit conversations stay yours.",
      lede: "Encryption, consent, and data rules that pass a compliance review on day one. Soft bureau only when the borrower says so.",
      items: [
        { t: "Encryption", d: "AES-256 at rest. TLS 1.3 in transit." },
        { t: "DPDP", d: "Designed around India’s Digital Personal Data Protection Act — purpose limitation, consent, and deletion." },
        { t: "Soft bureau", d: "No hard pull to shop options. Bureau access is consent-gated and logged." },
        { t: "Access", d: "Least-privilege roles. Production systems behind MFA." },
      ],
    },
    faq: {
      title: "Frequently asked questions",
      items: [
        {
          q: "What is Dhana?",
          a: "Dhana is the AI relationship manager for credit. Borrowers talk. She guides them through amount, purpose, EMI, offers, and KYC on the page. Lenders are partners. The product is PaisaOnClick, from Altiora Capital Solution Private Limited.",
        },
        {
          q: "Do I still fill a form?",
          a: "No. You speak. Dhana fills the application as you talk — the same idea as a guiding agent that acts on the page, applied to origination. If you prefer tapping, the fields are still there.",
        },
        {
          q: "Which languages does she speak?",
          a: "English, Hindi, Malayalam, Tamil, and Arabic, with more Indic languages on the roadmap. Switch the playground on this page to hear how the conversation rewrites.",
        },
        {
          q: "Are the rates on this page real offers?",
          a: "No. Comparison cards here are labelled illustrative. Live eligibility and rates come from lender partners after you talk to Dhana — never as fake quotes on a marketing page.",
        },
        {
          q: "How is my data handled?",
          a: "AES-256 at rest, TLS 1.3 in transit, DPDP-aligned consent, and a soft bureau pull only with explicit permission. We do not sell borrower conversations.",
        },
        {
          q: "Who is behind Dhana?",
          a: "Altiora Capital Solution Private Limited, Ernakulam, Kerala. CIN U63120KL2025PTC095578. GST 32ABDC2744E1Z7.",
        },
      ],
    },
    close: {
      title: "Ready when you are.",
      sub: "Talk through a loan the way you’d talk to an RM — then pick.",
      cta: "Talk to Dhana",
    },
    footer: {
      blurb: "Dhana is the AI relationship manager for credit. A product of PaisaOnClick.",
      company: "Altiora Capital Solution Private Limited",
      address: "The Office, 4th Floor, Jos Annex, Jos Junction, MG Road, Ernakulam South, Kerala 682016",
      cin: "CIN U63120KL2025PTC095578",
      gst: "GST 32ABDC2744E1Z7",
      product: "Product",
      companyLink: "Company",
      legal: "Legal",
    },
    float: "Talk to Dhana Agent",
  },
  hi: {
    nav: {
      product: "प्रोडक्ट",
      how: "कैसे काम करती है",
      lenders: "लेंडर्स",
      security: "सुरक्षा",
      faq: "सवाल",
      login: "लॉग इन",
      lendersCta: "लेंडर्स के लिए",
      talk: "Dhana से बात करें",
    },
    hero: {
      h1Before: "Voice AI for",
      h1Accent: "लोन.",
      sub: "भरोसे वाली क्रेडिट बातचीत के लिए बनी — जहाँ विश्वास सच में मायने रखता है।",
      cta: "Dhana से बात करें",
      metricStrong: "5,000+",
      metric: "उधारकर्ता",
      invite: "Dhana से बात करने के लिए क्लिक करें",
      mic: "माइक की अनुमति चाहिए",
      initiate: "कॉल शुरू करें",
      openLive: "लाइव Dhana खोलें",
    },
    useCases: [
      { id: "personal", kicker: "Dhana", label: "पर्सनल लोन", sub: "ज़िंदगी के खर्च" },
      { id: "home", kicker: "Dhana", label: "होम लोन", sub: "खरीदें, बनाएँ, सुधारें" },
      { id: "business", kicker: "Dhana", label: "बिज़नेस लोन", sub: "वर्किंग कैपिटल" },
      { id: "gold", kicker: "Dhana", label: "गोल्ड लोन", sub: "गहने पर" },
      { id: "unsure", kicker: "Dhana", label: "पक्का नहीं — बस बात करें", sub: "वो रास्ता निकाल लेगी" },
    ],
    call: {
      connecting: "कनेक्ट हो रहा है…",
      listening: "Dhana सुन रही है",
      speaking: "Dhana बोल रही है",
      muted: "म्यूट",
      hangup: "कॉल काटें",
      mute: "म्यूट",
      unmute: "अनम्यूट",
      denied: "माइक ब्लॉक है। लाइव डेमो फिर भी खोल सकते हैं।",
      scripts: {
        personal: [
          { who: "dhana", text: "नमस्ते, मैं Dhana हूँ। पर्सनल लोन — कितना चाहिए?" },
          { who: "you", text: "लगभग पाँच लाख।" },
          { who: "dhana", text: "₹5,00,000। लेंडर्स दिखाऊँ, या इस पेज पर आवेदन चलाएँ?" },
        ],
        home: [
          { who: "dhana", text: "होम लोन। खरीद, निर्माण, या रिनोवेशन?" },
          { who: "you", text: "रिनोवेशन। लगभग पाँच लाख।" },
          { who: "dhana", text: "ठीक है। राशि और मकसद रखती हूँ — फ़ॉर्म नहीं भरना।" },
        ],
        business: [
          { who: "dhana", text: "बिज़नेस लोन। वर्किंग कैपिटल?" },
          { who: "you", text: "हाँ। महीने के अठारह हज़ार दे सकती हूँ।" },
          { who: "dhana", text: "उसी EMI पर तीन उदाहरण ऑफ़र पेज पर रखूँगी।" },
        ],
        gold: [
          { who: "dhana", text: "गोल्ड लोन। पहले राशि, या अवधि?" },
          { who: "you", text: "राशि। पाँच लाख, अगर गहने कवर करें।" },
          { who: "dhana", text: "उसे ऊपरी सीमा मानकर कागज़ आपसे दूर रखूँगी।" },
        ],
        unsure: [
          { who: "dhana", text: "कोई बात नहीं। पैसे किस लिए चाहिए, अपने शब्दों में बताइए।" },
          { who: "you", text: "पाँच लाख चाहिए। कौन सा लोन, पता नहीं।" },
          { who: "dhana", text: "साथ में रास्ता चुनेंगे। पहले राशि, फिर मकसद, फिर EMI।" },
        ],
      },
    },
    trusted: "भारत में पहले से origination करने वाली टीमों के साथ।",
    partners: [
      "Axis Bank",
      "HDFC Bank",
      "SBI",
      "ICICI Bank",
      "Mahindra Finance",
      "Tata Capital",
    ],
    guided: {
      eyebrow: "गाइडेड origination",
      title: "वह लोन की बात नहीं करती। वह आवेदन चलाती है।",
      caption: "बात होते ही पेज भरता है। यह स्क्रिप्टेड डेमो है — ऑफ़र उदाहरण हैं, लाइव कोट नहीं।",
      play: "चलाएँ",
      pause: "रोकें",
      next: "आगे",
      prev: "पीछे",
      you: "आप",
      dhana: "Dhana",
      amountLabel: "राशि",
      purposeLabel: "मकसद",
      emiLabel: "मासिक EMI",
      offersLabel: "उदाहरण ऑफ़र",
      illustrative: "उदाहरण — लाइव कोट नहीं",
      closer: "आप चुनिए। गड़बड़ वाला हिस्सा Dhana ने कर दिया।",
      chips: ["घर सुधार", "मेडिकल", "शिक्षा", "अन्य"],
      offers: [
        { bank: "HDFC Bank", rate: "10.50%*", emi: "₹10,870", speed: "48 घंटे" },
        { bank: "Kotak", rate: "10.75%*", emi: "₹11,020", speed: "उसी दिन" },
        { bank: "Axis", rate: "11.00%*", emi: "₹11,180", speed: "24 घंटे" },
      ],
      steps: [
        { who: "you", text: "मुझे लगभग ₹5 लाख चाहिए।", action: "amount" },
        { who: "dhana", text: "किसके लिए — घर, मेडिकल, या और कुछ?", action: "purpose" },
        { who: "you", text: "महीने के ₹18,000 सँभाल सकती हूँ।", action: "emi" },
        { who: "dhana", text: "तीन साफ़ विकल्प। दर, EMI, disbursal देखिए।", action: "offers" },
        { who: "dhana", text: "आप चुनिए। गड़बड़ वाला हिस्सा Dhana ने कर दिया।", action: "close" },
      ],
    },
    how: {
      eyebrow: "कैसे काम करती है",
      title: "फ़ॉर्म नहीं। तीन कदम।",
      steps: [
        { n: "01", title: "बोलिए", body: "राशि, मकसद, कितनी EMI। जिस भाषा में आप बात करते हैं।" },
        { n: "02", title: "वह 50+ लेंडर्स जोड़ती है", body: "मैचिंग वह सँभालती है। आपको पोर्टल नहीं, छोटी सूची मिलती है।" },
        { n: "03", title: "आप चुनें / KYC", body: "ऑफ़र चुनें। KYC तब, जब लोन का आकार दिख जाए — पहले नहीं।" },
      ],
    },
    lending: {
      eyebrow: "लेंडिंग के लिए",
      title: "हर क्रेडिट बातचीत, एक रिलेशनशिप मैनेजर।",
      items: [
        { t: "पर्सनल", d: "अनसिक्योर्ड, मकसद के साथ, EMI पहले।" },
        { t: "होम", d: "खरीद, निर्माण, रिनोवेशन।" },
        { t: "बिज़नेस", d: "ब्रांच गए बिना वर्किंग कैपिटल।" },
        { t: "LAP", d: "प्रॉपर्टी पर लोन, आवाज़ में समझाया।" },
        { t: "वाहन", d: "कार और टू-व्हीलर, पुराने सहित।" },
        { t: "गोल्ड", d: "गहने पर, अवधि साधारण भाषा में।" },
        { t: "महिलाएँ", d: "महिला उधारकर्ताओं के प्रोडक्ट, नाम लेकर।" },
        { t: "कार्ड", d: "क्रेडिट कार्ड बिना बारह पन्नों के।" },
      ],
    },
    why: {
      eyebrow: "आवाज़, ब्रांच नहीं",
      title: "कतार से बात क्यों जीतती है।",
      items: [
        { t: "कोई टोकन नहीं", d: "रिलेशनशिप मैनेजर पेज पर है। 4:30 पर नहीं जाती।" },
        { t: "कागज़ दुश्मन है", d: "अयोग्य पता करने के लिए सत्रह फ़ील्ड नहीं। आप बोलते हैं। वह भरती है।" },
        { t: "भाषा ही प्रोडक्ट है", d: "मलयालम, हिंदी, तमिल, अंग्रेज़ी, अरबी। अंग्रेज़ी स्क्रिप्ट के बाद सबटाइटल नहीं।" },
      ],
    },
    security: {
      eyebrow: "रेगुलेटेड इंडस्ट्री",
      title: "क्रेडिट बातचीत आपकी रहती है।",
      lede: "एन्क्रिप्शन, सहमति, और डेटा नियम जो पहले दिन compliance से गुज़रें। सॉफ्ट ब्यूरो तभी, जब उधारकर्ता कहे।",
      items: [
        { t: "एन्क्रिप्शन", d: "आराम पर AES-256। रास्ते में TLS 1.3।" },
        { t: "DPDP", d: "भारत के डिजिटल पर्सनल डेटा प्रोटेक्शन एक्ट के इर्द-गिर्द — उद्देश्य, सहमति, मिटाना।" },
        { t: "सॉफ्ट ब्यूरो", d: "विकल्प देखने के लिए हार्ड पुल नहीं। ब्यूरो सहमति और लॉग के साथ।" },
        { t: "पहुँच", d: "कम-से-कम अधिकार। प्रोडक्शन पर MFA।" },
      ],
    },
    faq: {
      title: "अक्सर पूछे जाने वाले सवाल",
      items: [
        {
          q: "Dhana क्या है?",
          a: "Dhana क्रेडिट की AI रिलेशनशिप मैनेजर है। उधारकर्ता बोलते हैं। वह राशि, मकसद, EMI, ऑफ़र और KYC पेज पर चलाती है। लेंडर्स पार्टनर हैं। प्रोडक्ट PaisaOnClick है, Altiora Capital Solution Private Limited का।",
        },
        {
          q: "क्या फ़ॉर्म भरना पड़ेगा?",
          a: "नहीं। आप बोलते हैं। Dhana आवेदन भरती है — पेज पर काम करने वाले गाइडिंग एजेंट की तरह, origination पर। टैप करना हो तो फ़ील्ड मौजूद हैं।",
        },
        {
          q: "वह कौन सी भाषाएँ बोलती है?",
          a: "अंग्रेज़ी, हिंदी, मलयालम, तमिल और अरबी। इस पेज का playground बदलकर बातचीत देखें।",
        },
        {
          q: "क्या यहाँ की दरें असली ऑफ़र हैं?",
          a: "नहीं। तुलना कार्ड उदाहरण हैं। लाइव पात्रता और दरें लेंडर पार्टनर से आती हैं, मार्केटिंग पेज के नकली कोट से नहीं।",
        },
        {
          q: "डेटा कैसे सँभाला जाता है?",
          a: "आराम पर AES-256, TLS 1.3, DPDP-अनुकूल सहमति, और सॉफ्ट ब्यूरो केवल इजाज़त के साथ। बातचीत नहीं बेची जाती।",
        },
        {
          q: "Dhana के पीछे कौन है?",
          a: "Altiora Capital Solution Private Limited, एर्णाकुलम, केरल। CIN U63120KL2025PTC095578. GST 32ABDC2744E1Z7.",
        },
      ],
    },
    close: {
      title: "जब आप तैयार हों।",
      sub: "RM से जैसी बात होती है, वैसी — फिर चुनिए।",
      cta: "Dhana से बात करें",
    },
    footer: {
      blurb: "Dhana क्रेडिट की AI रिलेशनशिप मैनेजर है। PaisaOnClick का प्रोडक्ट।",
      company: "Altiora Capital Solution Private Limited",
      address: "The Office, 4th Floor, Jos Annex, Jos Junction, MG Road, Ernakulam South, Kerala 682016",
      cin: "CIN U63120KL2025PTC095578",
      gst: "GST 32ABDC2744E1Z7",
      product: "प्रोडक्ट",
      companyLink: "कंपनी",
      legal: "कानूनी",
    },
    float: "Dhana एजेंट से बात करें",
  },
  ml: {
    nav: {
      product: "ഉൽപ്പന്നം",
      how: "എങ്ങനെ",
      lenders: "ലെൻഡർമാർ",
      security: "സുരക്ഷ",
      faq: "ചോദ്യങ്ങൾ",
      login: "ലോഗിൻ",
      lendersCta: "ലെൻഡർമാർക്ക്",
      talk: "Dhanaയോട് സംസാരിക്കുക",
    },
    hero: {
      h1Before: "Voice AI for",
      h1Accent: "വായ്പ.",
      sub: "വിശ്വാസം ശരിക്കും പ്രശ്നമാകുന്ന ക്രെഡിറ്റ് സംഭാഷണങ്ങൾക്കായി നിർമ്മിച്ചത്.",
      cta: "Dhanaയോട് സംസാരിക്കുക",
      metricStrong: "5,000+",
      metric: "കടം വാങ്ങിയവർ",
      invite: "Dhanaയോട് സംസാരിക്കാൻ ക്ലിക്ക് ചെയ്യുക",
      mic: "മൈക്ക് അനുമതി വേണം",
      initiate: "കോൾ തുടങ്ങുക",
      openLive: "ലൈവ് Dhana തുറക്കുക",
    },
    useCases: [
      { id: "personal", kicker: "Dhana", label: "പേഴ്‌സണൽ ലോൺ", sub: "ജീവിതത്തിനുള്ള പണം" },
      { id: "home", kicker: "Dhana", label: "ഹോം ലോൺ", sub: "വാങ്ങുക, പണിയുക, നന്നാക്കുക" },
      { id: "business", kicker: "Dhana", label: "ബിസിനസ് ലോൺ", sub: "വർക്കിങ് ക്യാപിറ്റൽ" },
      { id: "gold", kicker: "Dhana", label: "ഗോൾഡ് ലോൺ", sub: "ആഭരണം ഈടായി" },
      { id: "unsure", kicker: "Dhana", label: "ഉറപ്പില്ല — സംസാരിക്കാം", sub: "അവൾ വഴി കണ്ടെത്തും" },
    ],
    call: {
      connecting: "ബന്ധിപ്പിക്കുന്നു…",
      listening: "Dhana കേൾക്കുന്നു",
      speaking: "Dhana സംസാരിക്കുന്നു",
      muted: "മ്യൂട്ട്",
      hangup: "വെട്ടുക",
      mute: "മ്യൂട്ട്",
      unmute: "അൺമ്യൂട്ട്",
      denied: "മൈക്ക് തടഞ്ഞു. ലൈവ് ഡെമോ തുറക്കാം.",
      scripts: {
        personal: [
          { who: "dhana", text: "ഹായ്, ഞാൻ Dhana. പേഴ്‌സണൽ ലോൺ — എത്ര വേണം?" },
          { who: "you", text: "ഏകദേശം അഞ്ച് ലക്ഷം." },
          { who: "dhana", text: "₹5,00,000. ലെൻഡർമാരെ കാണിക്കാം, അല്ലെങ്കിൽ ഈ പേജിൽ അപേക്ഷ നടത്താം." },
        ],
        home: [
          { who: "dhana", text: "ഹോം ലോൺ. വാങ്ങലോ, പണിയലോ, നന്നാക്കലോ?" },
          { who: "you", text: "നന്നാക്കൽ. അഞ്ച് ലക്ഷത്തോളം." },
          { who: "dhana", text: "ശരി. തുകയും ഉദ്ദേശ്യവും ഞാൻ പിടിക്കും — ഫോം ഇല്ല." },
        ],
        business: [
          { who: "dhana", text: "ബിസിനസ് ലോൺ. വർക്കിങ് ക്യാപിറ്റലോ?" },
          { who: "you", text: "അതെ. മാസം പതിനെട്ടായിരം കൊടുക്കാം." },
          { who: "dhana", text: "ആ EMI-ക്ക് മൂന്ന് ഉദാഹരണ ഓഫറുകൾ പേജിൽ വയ്ക്കാം." },
        ],
        gold: [
          { who: "dhana", text: "ഗോൾഡ് ലോൺ. ആദ്യം തുകയോ കാലാവധിയോ?" },
          { who: "you", text: "തുക. ആഭരണം മതിയെങ്കിൽ അഞ്ച് ലക്ഷം." },
          { who: "dhana", text: "അത് പരിധിയായി വെച്ച് കടലാസ് നിങ്ങളിൽ നിന്ന് മാറ്റി നിർത്താം." },
        ],
        unsure: [
          { who: "dhana", text: "പ്രശ്നമില്ല. പണം എന്തിന് എന്ന് നിങ്ങളുടെ വാക്കുകളിൽ പറയൂ." },
          { who: "you", text: "അഞ്ച് ലക്ഷം വേണം. ഏത് ലോൺ എന്നറിയില്ല." },
          { who: "dhana", text: "കൂടെ ഒരു വഴി തെരഞ്ഞെടുക്കാം. തുക, ഉദ്ദേശ്യം, പിന്നെ EMI." },
        ],
      },
    },
    trusted: "ഇന്ത്യയിൽ ഇതിനകം origination നടത്തുന്ന ടീമുകൾക്കൊപ്പം.",
    partners: [
      "Axis Bank",
      "HDFC Bank",
      "SBI",
      "ICICI Bank",
      "Mahindra Finance",
      "Tata Capital",
    ],
    guided: {
      eyebrow: "ഗൈഡഡ് origination",
      title: "അവൾ വായ്പയെക്കുറിച്ച് ചാറ്റ് ചെയ്യുന്നില്ല. അപേക്ഷ നടത്തുന്നു.",
      caption: "സംസാരം നടക്കുമ്പോൾ പേജ് നിറയുന്നു. സ്ക്രിപ്റ്റഡ് ഡെമോ — ഓഫറുകൾ ഉദാഹരണം, ലൈവ് ക്വോട്ടല്ല.",
      play: "പ്ലേ",
      pause: "നിർത്തുക",
      next: "അടുത്തത്",
      prev: "പിന്നോട്ട്",
      you: "നിങ്ങൾ",
      dhana: "Dhana",
      amountLabel: "തുക",
      purposeLabel: "ഉദ്ദേശ്യം",
      emiLabel: "മാസ EMI",
      offersLabel: "ഉദാഹരണ ഓഫറുകൾ",
      illustrative: "ഉദാഹരണം — ലൈവ് ക്വോട്ടല്ല",
      closer: "നിങ്ങൾ തെരഞ്ഞെടുക്കൂ. കുഴപ്പമുള്ള ഭാഗം Dhana കഴിച്ചു.",
      chips: ["വീട് നന്നാക്കൽ", "മെഡിക്കൽ", "വിദ്യാഭ്യാസം", "മറ്റുള്ളത്"],
      offers: [
        { bank: "HDFC Bank", rate: "10.50%*", emi: "₹10,870", speed: "48 മണിക്കൂർ" },
        { bank: "Kotak", rate: "10.75%*", emi: "₹11,020", speed: "അന്നുതന്നെ" },
        { bank: "Axis", rate: "11.00%*", emi: "₹11,180", speed: "24 മണിക്കൂർ" },
      ],
      steps: [
        { who: "you", text: "ഏകദേശം ₹5 ലക്ഷം വേണം.", action: "amount" },
        { who: "dhana", text: "എന്തിന് — വീട്, മെഡിക്കൽ, അതോ മറ്റോ?", action: "purpose" },
        { who: "you", text: "മാസം ₹18,000 കൈകാര്യം ചെയ്യാം.", action: "emi" },
        { who: "dhana", text: "മൂന്ന് വ്യക്തമായ ഓപ്ഷനുകൾ. നിരക്ക്, EMI, disbursal.", action: "offers" },
        { who: "dhana", text: "നിങ്ങൾ തെരഞ്ഞെടുക്കൂ. കുഴപ്പമുള്ള ഭാഗം Dhana കഴിച്ചു.", action: "close" },
      ],
    },
    how: {
      eyebrow: "എങ്ങനെ",
      title: "ഫോം ഇല്ല. മൂന്ന് ചുവടുകൾ.",
      steps: [
        { n: "01", title: "പറയൂ", body: "തുക, ഉദ്ദേശ്യം, എത്ര EMI. നിങ്ങൾ ഇപ്പോൾ സംസാരിക്കുന്ന ഭാഷയിൽ." },
        { n: "02", title: "50+ ലെൻഡർമാരെ ഒത്തുനോക്കുന്നു", body: "മാച്ചിങ് അവൾ സംരക്ഷിക്കുന്നു. പോർട്ടലല്ല, ചെറിയ ലിസ്റ്റ്." },
        { n: "03", title: "നിങ്ങൾ തെരഞ്ഞെടുക്കൂ / KYC", body: "ഓഫർ തെരഞ്ഞെടുക്കുക. വായ്പയുടെ രൂപം കണ്ട ശേഷം KYC — മുമ്പല്ല." },
      ],
    },
    lending: {
      eyebrow: "ലെൻഡിങ്ങിനായി",
      title: "ഓരോ ക്രെഡിറ്റ് സംസാരവും, ഒരു റിലേഷൻഷിപ് മാനേജർ.",
      items: [
        { t: "പേഴ്‌സണൽ", d: "അൺസെക്യുർഡ്, ഉദ്ദേശ്യത്തോടെ, EMI ആദ്യം." },
        { t: "ഹോം", d: "വാങ്ങൽ, നിർമാണം, നന്നാക്കൽ." },
        { t: "ബിസിനസ്", d: "ബ്രാഞ്ചില്ലാതെ വർക്കിങ് ക്യാപിറ്റൽ." },
        { t: "LAP", d: "പ്രോപ്പർട്ടിക്കെതിരെ വായ്പ, ഉറക്കെ വിശദീകരിക്കും." },
        { t: "വാഹനം", d: "കാർ, ടൂ-വീലർ, ഉപയോഗിച്ചവയും." },
        { t: "ഗോൾഡ്", d: "ആഭരണത്തിനെതിരെ, കാലാവധി ലളിതമായി." },
        { t: "സ്ത്രീകൾ", d: "സ്ത്രീ കടം വാങ്ങുന്നവർക്കുള്ള ഉൽപ്പന്നങ്ങൾ." },
        { t: "കാർഡ്", d: "പന്ത്രണ്ട് പേജില്ലാത്ത ക്രെഡിറ്റ് കാർഡ്." },
      ],
    },
    why: {
      eyebrow: "ശബ്ദം, ബ്രാഞ്ചല്ല",
      title: "ക്യൂവിനെ സംസാരം എന്തുകൊണ്ട് തോൽപ്പിക്കുന്നു.",
      items: [
        { t: "ടോക്കണില്ല", d: "റിലേഷൻഷിപ് മാനേജർ പേജിലുണ്ട്. 4:30-ന് അടയ്ക്കുന്നില്ല." },
        { t: "കടലാസ് ശത്രുവാണ്", d: "യോഗ്യത ഇല്ലെന്ന് അറിയാൻ പതിനേഴ് ഫീൽഡില്ല. നിങ്ങൾ പറയും. അവൾ നിറയ്ക്കും." },
        { t: "ഭാഷ തന്നെ ഉൽപ്പന്നം", d: "മലയാളം, ഹിന്ദി, തമിഴ്, ഇംഗ്ലീഷ്, അറബി. ഇംഗ്ലീഷ് സ്ക്രിപ്റ്റിന് ശേഷമുള്ള സബ്‌ടൈറ്റിലല്ല." },
      ],
    },
    security: {
      eyebrow: "റെഗുലേറ്റഡ് വ്യവസായം",
      title: "ക്രെഡിറ്റ് സംസാരം നിങ്ങളുടേത് തന്നെ.",
      lede: "ആദ്യ ദിവസം compliance കടന്നുപോകുന്ന എൻക്രിപ്ഷൻ, സമ്മതം, ഡാറ്റ നിയമങ്ങൾ. സോഫ്റ്റ് ബ്യൂറോ കടം വാങ്ങുന്നയാൾ പറയുമ്പോൾ മാത്രം.",
      items: [
        { t: "എൻക്രിപ്ഷൻ", d: "വിശ്രമത്തിൽ AES-256. വഴിയിൽ TLS 1.3." },
        { t: "DPDP", d: "ഇന്ത്യയുടെ ഡിജിറ്റൽ പേഴ്‌സണൽ ഡാറ്റ പ്രൊട്ടക്ഷൻ ആക്ട് — ഉദ്ദേശ്യം, സമ്മതം, മായ്ക്കൽ." },
        { t: "സോഫ്റ്റ് ബ്യൂറോ", d: "ഓപ്ഷൻ കാണാൻ ഹാർഡ് പുൾ ഇല്ല. ബ്യൂറോ സമ്മതത്തോടെയും ലോഗോടെയും." },
        { t: "ആക്‌സസ്", d: "കുറഞ്ഞ അവകാശം. പ്രൊഡക്ഷനിൽ MFA." },
      ],
    },
    faq: {
      title: "പതിവ് ചോദ്യങ്ങൾ",
      items: [
        {
          q: "Dhana എന്താണ്?",
          a: "Dhana ക്രെഡിറ്റിനുള്ള AI റിലേഷൻഷിപ് മാനേജറാണ്. കടം വാങ്ങുന്നവർ സംസാരിക്കുന്നു. തുക, ഉദ്ദേശ്യം, EMI, ഓഫർ, KYC അവൾ പേജിൽ നടത്തുന്നു. ലെൻഡർമാർ പങ്കാളികൾ. ഉൽപ്പന്നം PaisaOnClick, Altiora Capital Solution Private Limited.",
        },
        {
          q: "ഫോം നിറയ്ക്കണോ?",
          a: "വേണ്ട. നിങ്ങൾ സംസാരിക്കുക. Dhana അപേക്ഷ നിറയ്ക്കുന്നു. ടാപ്പ് ചെയ്യണമെങ്കിൽ ഫീൽഡുകളുണ്ട്.",
        },
        {
          q: "ഏത് ഭാഷകൾ?",
          a: "ഇംഗ്ലീഷ്, ഹിന്ദി, മലയാളം, തമിഴ്, അറബി. ഈ പേജിലെ playground മാറ്റി സംസാരം കാണുക.",
        },
        {
          q: "ഇവിടത്തെ നിരക്ക് യഥാർത്ഥ ഓഫറാണോ?",
          a: "അല്ല. താരതമ്യ കാർഡുകൾ ഉദാഹരണമാണ്. യഥാർത്ഥ യോഗ്യത ലെൻഡർ പങ്കാളികളിൽ നിന്ന്.",
        },
        {
          q: "ഡാറ്റ എങ്ങനെ?",
          a: "AES-256, TLS 1.3, DPDP സമ്മതം, സോഫ്റ്റ് ബ്യൂറോ അനുവാദത്തോടെ മാത്രം. സംസാരം വിറ്റഴിക്കില്ല.",
        },
        {
          q: "പിന്നിൽ ആര്?",
          a: "Altiora Capital Solution Private Limited, എറണാകുളം, കേരളം. CIN U63120KL2025PTC095578. GST 32ABDC2744E1Z7.",
        },
      ],
    },
    close: {
      title: "തയ്യാറാകുമ്പോൾ.",
      sub: "ഒരു RM-നോട് സംസാരിക്കുന്ന പോലെ — പിന്നെ തെരഞ്ഞെടുക്കുക.",
      cta: "Dhanaയോട് സംസാരിക്കുക",
    },
    footer: {
      blurb: "Dhana ക്രെഡിറ്റിനുള്ള AI റിലേഷൻഷിപ് മാനേജറാണ്. PaisaOnClick-ന്റെ ഉൽപ്പന്നം.",
      company: "Altiora Capital Solution Private Limited",
      address: "The Office, 4th Floor, Jos Annex, Jos Junction, MG Road, Ernakulam South, Kerala 682016",
      cin: "CIN U63120KL2025PTC095578",
      gst: "GST 32ABDC2744E1Z7",
      product: "ഉൽപ്പന്നം",
      companyLink: "കമ്പനി",
      legal: "നിയമം",
    },
    float: "Dhana ഏജന്റിനോട് സംസാരിക്കുക",
  },
  ta: {
    nav: {
      product: "தயாரிப்பு",
      how: "எப்படி",
      lenders: "கடன் வழங்குநர்கள்",
      security: "பாதுகாப்பு",
      faq: "கேள்விகள்",
      login: "உள்நுழை",
      lendersCta: "வழங்குநர்களுக்கு",
      talk: "Dhanaவிடம் பேசுங்கள்",
    },
    hero: {
      h1Before: "Voice AI for",
      h1Accent: "கடன்.",
      sub: "நம்பிக்கை உண்மையில் முக்கியம் ஆகும் கடன் உரையாடல்களுக்காக உருவாக்கப்பட்டது.",
      cta: "Dhanaவிடம் பேசுங்கள்",
      metricStrong: "5,000+",
      metric: "கடன் வாங்கியோர்",
      invite: "Dhanaவிடம் பேச கிளிக் செய்யவும்",
      mic: "மைக் அனுமதி தேவை",
      initiate: "அழைப்பைத் தொடங்கு",
      openLive: "நேரடி Dhanaவைத் திற",
    },
    useCases: [
      { id: "personal", kicker: "Dhana", label: "தனிநபர் கடன்", sub: "வாழ்க்கைக்கான பணம்" },
      { id: "home", kicker: "Dhana", label: "வீட்டுக் கடன்", sub: "வாங்கு, கட்டு, புதுப்பி" },
      { id: "business", kicker: "Dhana", label: "வணிகக் கடன்", sub: "பணி மூலதனம்" },
      { id: "gold", kicker: "Dhana", label: "தங்கக் கடன்", sub: "நகைக்கு எதிராக" },
      { id: "unsure", kicker: "Dhana", label: "தெரியவில்லை — பேசுங்கள்", sub: "அவள் வழியைக் கண்டுபிடிப்பாள்" },
    ],
    call: {
      connecting: "இணைக்கிறது…",
      listening: "Dhana கேட்கிறாள்",
      speaking: "Dhana பேசுகிறாள்",
      muted: "முடக்கம்",
      hangup: "துண்டி",
      mute: "முடக்கு",
      unmute: "முடக்கத்தை நீக்கு",
      denied: "மைக் தடுக்கப்பட்டது. நேரடி டெமோவைத் திறக்கலாம்.",
      scripts: {
        personal: [
          { who: "dhana", text: "வணக்கம், நான் Dhana. தனிநபர் கடன் — எவ்வளவு வேண்டும்?" },
          { who: "you", text: "சுமார் ஐந்து லட்சம்." },
          { who: "dhana", text: "₹5,00,000. வழங்குநர்களைக் காட்டட்டுமா, அல்லது இந்தப் பக்கத்தில் விண்ணப்பமா?" },
        ],
        home: [
          { who: "dhana", text: "வீட்டுக் கடன். வாங்கலா, கட்டலா, புதுப்பிக்கலா?" },
          { who: "you", text: "புதுப்பிப்பு. சுமார் ஐந்து லட்சம்." },
          { who: "dhana", text: "சரி. தொகையையும் நோக்கத்தையும் வைத்துக்கொள்கிறேன் — படிவம் இல்லை." },
        ],
        business: [
          { who: "dhana", text: "வணிகக் கடன். பணி மூலதனமா?" },
          { who: "you", text: "ஆம். மாதம் பதினெட்டாயிரம் செலுத்த முடியும்." },
          { who: "dhana", text: "அந்த EMI-க்கு மூன்று எடுத்துக்காட்டு சலுகைகளைப் பக்கத்தில் வைக்கிறேன்." },
        ],
        gold: [
          { who: "dhana", text: "தங்கக் கடன். முதலில் தொகையா, காலமா?" },
          { who: "you", text: "தொகை. நகை போதுமானால் ஐந்து லட்சம்." },
          { who: "dhana", text: "அதை உச்சவரம்பாக வைத்து காகிதத்தை உங்களிடமிருந்து விலக்கி வைக்கிறேன்." },
        ],
        unsure: [
          { who: "dhana", text: "பரவாயில்லை. பணம் எதற்கு என்று உங்கள் வார்த்தைகளில் சொல்லுங்கள்." },
          { who: "you", text: "ஐந்து லட்சம் வேண்டும். எந்தக் கடன் என்று தெரியவில்லை." },
          { who: "dhana", text: "சேர்ந்து ஒரு பாதையைத் தேர்ந்தெடுப்போம். தொகை, நோக்கம், பிறகு EMI." },
        ],
      },
    },
    trusted: "இந்தியாவில் ஏற்கனவே origination செய்யும் குழுக்களுடன்.",
    partners: [
      "Axis Bank",
      "HDFC Bank",
      "SBI",
      "ICICI Bank",
      "Mahindra Finance",
      "Tata Capital",
    ],
    guided: {
      eyebrow: "வழிநடத்தும் origination",
      title: "அவள் கடனைப் பற்றி அரட்டாடுவதில்லை. விண்ணப்பத்தை நடத்துகிறாள்.",
      caption: "உரையாடல் நடக்கும்போது பக்கம் நிறையும். இது ஸ்கிரிப்ட் டெமோ — சலுகைகள் எடுத்துக்காட்டு, நேரடி மேற்கோள் அல்ல.",
      play: "இயக்கு",
      pause: "இடைநிறுத்து",
      next: "அடுத்து",
      prev: "பின்",
      you: "நீங்கள்",
      dhana: "Dhana",
      amountLabel: "தொகை",
      purposeLabel: "நோக்கம்",
      emiLabel: "மாதாந்திர EMI",
      offersLabel: "எடுத்துக்காட்டு சலுகைகள்",
      illustrative: "எடுத்துக்காட்டு — நேரடி மேற்கோள் அல்ல",
      closer: "நீங்கள் தேர்ந்தெடுங்கள். சிக்கலான பகுதியை Dhana முடித்துவிட்டாள்.",
      chips: ["வீட்டு புதுப்பிப்பு", "மருத்துவம்", "கல்வி", "மற்றவை"],
      offers: [
        { bank: "HDFC Bank", rate: "10.50%*", emi: "₹10,870", speed: "48 மணி" },
        { bank: "Kotak", rate: "10.75%*", emi: "₹11,020", speed: "அன்றே" },
        { bank: "Axis", rate: "11.00%*", emi: "₹11,180", speed: "24 மணி" },
      ],
      steps: [
        { who: "you", text: "சுமார் ₹5 லட்சம் வேண்டும்.", action: "amount" },
        { who: "dhana", text: "எதற்கு — வீடு, மருத்துவம், அல்லது வேறு?", action: "purpose" },
        { who: "you", text: "மாதம் ₹18,000 சமாளிக்க முடியும்.", action: "emi" },
        { who: "dhana", text: "மூன்று தெளிவான விருப்பங்கள். வீதம், EMI, disbursal.", action: "offers" },
        { who: "dhana", text: "நீங்கள் தேர்ந்தெடுங்கள். சிக்கலான பகுதியை Dhana முடித்துவிட்டாள்.", action: "close" },
      ],
    },
    how: {
      eyebrow: "எப்படி",
      title: "படிவம் இல்லை. மூன்று அடிகள்.",
      steps: [
        { n: "01", title: "சொல்லுங்கள்", body: "தொகை, நோக்கம், எவ்வளவு EMI. நீங்கள் பேசும் மொழியில்." },
        { n: "02", title: "50+ வழங்குநர்களை ஒப்பிடுகிறாள்", body: "பொருத்துதலை அவள் செய்வாள். போர்ட்டல் அல்ல, சிறிய பட்டியல்." },
        { n: "03", title: "நீங்கள் தேர்வு / KYC", body: "சலுகையைத் தேர்ந்தெடுங்கள். கடனின் வடிவம் தெரிந்த பிறகு KYC — முன்னரல்ல." },
      ],
    },
    lending: {
      eyebrow: "கடனுக்காக",
      title: "ஒவ்வொரு கடன் உரையாடலும், ஒரு உறவு மேலாளர்.",
      items: [
        { t: "தனிநபர்", d: "அடகு இல்லாமல், நோக்கத்துடன், EMI முதலில்." },
        { t: "வீடு", d: "வாங்குதல், கட்டுதல், புதுப்பித்தல்." },
        { t: "வணிகம்", d: "கிளைக்குப் போகாமல் பணி மூலதனம்." },
        { t: "LAP", d: "சொத்துக்கு எதிரான கடன், சத்தமாக விளக்கம்." },
        { t: "வாகனம்", d: "கார் மற்றும் இருசக்கரம், பயன்படுத்தியவை உட்பட." },
        { t: "தங்கம்", d: "நகைக்கு எதிராக, காலம் எளிய மொழியில்." },
        { t: "பெண்கள்", d: "பெண் கடன் வாங்குவோருக்கான தயாரிப்புகள்." },
        { t: "அட்டை", d: "பன்னிரண்டு பக்கம் இல்லாத கிரெடிட் கார்டு." },
      ],
    },
    why: {
      eyebrow: "குரல், கிளை அல்ல",
      title: "வரிசையைப் பேச்சு ஏன் வெல்கிறது.",
      items: [
        { t: "டோக்கன் இல்லை", d: "உறவு மேலாளர் பக்கத்தில் இருக்கிறாள். 4:30க்கு மூடமாட்டாள்." },
        { t: "காகிதம் எதிரி", d: "தகுதியில்லை என்று அறிய பதினேழு புலங்கள் இல்லை. நீங்கள் பேசுவீர்கள். அவள் நிரப்புவாள்." },
        { t: "மொழியே தயாரிப்பு", d: "மலையாளம், இந்தி, தமிழ், ஆங்கிலம், அரபு. ஆங்கில ஸ்கிரிப்ட்டுக்குப் பின் வரும் வரிமொழி அல்ல." },
      ],
    },
    security: {
      eyebrow: "ஒழுங்குபடுத்தப்பட்ட தொழில்",
      title: "கடன் உரையாடல் உங்களுடையதே.",
      lede: "முதல் நாளிலேயே compliance கடக்கும் குறியாக்கம், ஒப்புதல், தரவு விதிகள். மென்மையான பீரோ கடன் வாங்குபவர் சொன்னால் மட்டுமே.",
      items: [
        { t: "குறியாக்கம்", d: "ஓய்வில் AES-256. பாதையில் TLS 1.3." },
        { t: "DPDP", d: "இந்தியாவின் டிஜிட்டல் தனிப்பட்ட தரவு பாதுகாப்புச் சட்டம் — நோக்கம், ஒப்புதல், நீக்கம்." },
        { t: "மென் பீரோ", d: "விருப்பங்களைப் பார்க்க கடினப் இழுப்பு இல்லை. பீரோ ஒப்புதல் மற்றும் பதிவுடன்." },
        { t: "அணுகல்", d: "குறைந்த உரிமை. தயாரிப்பில் MFA." },
      ],
    },
    faq: {
      title: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
      items: [
        {
          q: "Dhana என்றால் என்ன?",
          a: "Dhana கடனுக்கான AI உறவு மேலாளர். கடன் வாங்குவோர் பேசுவர். தொகை, நோக்கம், EMI, சலுகை, KYC ஆகியவற்றை அவள் பக்கத்தில் நடத்துவாள். வழங்குநர்கள் கூட்டாளிகள். தயாரிப்பு PaisaOnClick, Altiora Capital Solution Private Limited.",
        },
        {
          q: "படிவம் நிரப்ப வேண்டுமா?",
          a: "இல்லை. நீங்கள் பேசுங்கள். Dhana விண்ணப்பத்தை நிரப்புவாள். தட்ட விரும்பினால் புலங்கள் உள்ளன.",
        },
        {
          q: "எந்த மொழிகள்?",
          a: "ஆங்கிலம், இந்தி, மலையாளம், தமிழ், அரபு. இந்தப் பக்க playground-ஐ மாற்றி உரையாடலைப் பாருங்கள்.",
        },
        {
          q: "இங்குள்ள வீதங்கள் உண்மையான சலுகையா?",
          a: "இல்லை. ஒப்பீட்டு அட்டைகள் எடுத்துக்காட்டு. நேரடி தகுதி வழங்குநர் கூட்டாளிகளிடமிருந்து.",
        },
        {
          q: "தரவு எப்படி?",
          a: "AES-256, TLS 1.3, DPDP ஒப்புதல், மென் பீரோ அனுமதியுடன் மட்டுமே. உரையாடலை விற்கமாட்டோம்.",
        },
        {
          q: "பின்னால் யார்?",
          a: "Altiora Capital Solution Private Limited, எர்ணாகுளம், கேரளா. CIN U63120KL2025PTC095578. GST 32ABDC2744E1Z7.",
        },
      ],
    },
    close: {
      title: "நீங்கள் தயாரானதும்.",
      sub: "ஒரு RM-இடம் பேசுவது போல — பிறகு தேர்ந்தெடுங்கள்.",
      cta: "Dhanaவிடம் பேசுங்கள்",
    },
    footer: {
      blurb: "Dhana கடனுக்கான AI உறவு மேலாளர். PaisaOnClick தயாரிப்பு.",
      company: "Altiora Capital Solution Private Limited",
      address: "The Office, 4th Floor, Jos Annex, Jos Junction, MG Road, Ernakulam South, Kerala 682016",
      cin: "CIN U63120KL2025PTC095578",
      gst: "GST 32ABDC2744E1Z7",
      product: "தயாரிப்பு",
      companyLink: "நிறுவனம்",
      legal: "சட்டம்",
    },
    float: "Dhana முகவரிடம் பேசுங்கள்",
  },
  ar: {
    nav: {
      product: "المنتج",
      how: "كيف تعمل",
      lenders: "المقرضون",
      security: "الأمان",
      faq: "أسئلة",
      login: "دخول",
      lendersCta: "للمقرضين",
      talk: "تحدث إلى دهانا",
    },
    hero: {
      h1Before: "Voice AI for",
      h1Accent: "الإقراض.",
      sub: "مبنية لمحادثات الائتمان عالية المخاطر حيث تهم الثقة فعلاً.",
      cta: "تحدث إلى دهانا",
      metricStrong: "5,000+",
      metric: "مقترض",
      invite: "انقر للتحدث مع دهانا",
      mic: "يلزم إذن الميكروفون",
      initiate: "بدء المكالمة",
      openLive: "افتح دهانا مباشرة",
    },
    useCases: [
      { id: "personal", kicker: "دهانا", label: "قرض شخصي", sub: "مال للحياة" },
      { id: "home", kicker: "دهانا", label: "قرض سكني", sub: "شراء أو بناء أو تجديد" },
      { id: "business", kicker: "دهانا", label: "قرض تجاري", sub: "رأس مال عامل" },
      { id: "gold", kicker: "دهانا", label: "قرض ذهب", sub: "مقابل المجوهرات" },
      { id: "unsure", kicker: "دهانا", label: "لست متأكدًا — فقط تحدّث", sub: "ستجد الطريق" },
    ],
    call: {
      connecting: "جارٍ الاتصال…",
      listening: "دهانا تستمع",
      speaking: "دهانا تتحدث",
      muted: "صامت",
      hangup: "إنهاء",
      mute: "كتم",
      unmute: "إلغاء الكتم",
      denied: "الميكروفون محظور. يمكنك فتح العرض الحي.",
      scripts: {
        personal: [
          { who: "dhana", text: "مرحبًا، أنا دهانا. قرض شخصي — كم تحتاج؟" },
          { who: "you", text: "حوالي خمسة لكح." },
          { who: "dhana", text: "₹5,00,000. أعرض المقرضين، أو ندير الطلب على هذه الصفحة؟" },
        ],
        home: [
          { who: "dhana", text: "قرض سكني. شراء أم بناء أم تجديد؟" },
          { who: "you", text: "تجديد. حوالي خمسة لكح." },
          { who: "dhana", text: "حسنًا. أحتفظ بالمبلغ والغرض — بلا نموذج." },
        ],
        business: [
          { who: "dhana", text: "قرض تجاري. رأس مال عامل؟" },
          { who: "you", text: "نعم. أستطيع دفع ثمانية عشر ألفًا شهريًا." },
          { who: "dhana", text: "سأضع ثلاثة عروض توضيحية على الصفحة وفق ذلك القسط." },
        ],
        gold: [
          { who: "dhana", text: "قرض ذهب. المبلغ أولًا أم المدة؟" },
          { who: "you", text: "المبلغ. خمسة لكح إذا غطّت المجوهرات." },
          { who: "dhana", text: "نعامله حدًا أعلى ونُبقي الأوراق بعيدة عنك." },
        ],
        unsure: [
          { who: "dhana", text: "لا بأس. قل لي لماذا تحتاج المال، بكلماتك." },
          { who: "you", text: "أحتاج خمسة لكح. لا أعرف أي قرض." },
          { who: "dhana", text: "نختار مسارًا معًا. المبلغ، ثم الغرض، ثم القسط." },
        ],
      },
    },
    trusted: "موثوق به لدى فرق تُنشئ القروض في الهند.",
    partners: [
      "Axis Bank",
      "HDFC Bank",
      "SBI",
      "ICICI Bank",
      "Mahindra Finance",
      "Tata Capital",
    ],
    guided: {
      eyebrow: "تأسيس موجَّه",
      title: "هي لا تدردش عن القروض. هي تدير الطلب.",
      caption: "شاهد الصفحة تُملأ أثناء الحديث. عرض مُعدّ — العروض توضيحية وليست أسعارًا حية.",
      play: "تشغيل",
      pause: "إيقاف",
      next: "التالي",
      prev: "رجوع",
      you: "أنت",
      dhana: "دهانا",
      amountLabel: "المبلغ",
      purposeLabel: "الغرض",
      emiLabel: "القسط الشهري",
      offersLabel: "عروض توضيحية",
      illustrative: "توضيحي — ليس عرضًا حيًا",
      closer: "أنت تختار. دهانا أنهت الجزء المُربك.",
      chips: ["تجديد المنزل", "طبي", "تعليم", "أخرى"],
      offers: [
        { bank: "HDFC Bank", rate: "10.50%*", emi: "₹10,870", speed: "48 ساعة" },
        { bank: "Kotak", rate: "10.75%*", emi: "₹11,020", speed: "نفس اليوم" },
        { bank: "Axis", rate: "11.00%*", emi: "₹11,180", speed: "24 ساعة" },
      ],
      steps: [
        { who: "you", text: "أحتاج حوالي ₹5 لكح.", action: "amount" },
        { who: "dhana", text: "لماذا — منزل، طبي، أم شيء آخر؟", action: "purpose" },
        { who: "you", text: "أستطيع تدبير ₹18,000 شهريًا.", action: "emi" },
        { who: "dhana", text: "ثلاثة خيارات واضحة. قارن السعر والقسط والصرف.", action: "offers" },
        { who: "dhana", text: "أنت تختار. دهانا أنهت الجزء المُربك.", action: "close" },
      ],
    },
    how: {
      eyebrow: "كيف تعمل",
      title: "بلا نماذج. ثلاث خطوات.",
      steps: [
        { n: "01", title: "قلها", body: "المبلغ والغرض وما تستطيع دفعه. باللغة التي تستخدمها أصلًا." },
        { n: "02", title: "تقارن أكثر من 50 مقرضًا", body: "هي تتولى المطابقة. ترى قائمة قصيرة لا بوابة." },
        { n: "03", title: "تختار / KYC", body: "اختر عرضًا. أكمل KYC عندما تكون جاهزًا — لا قبل أن ترى شكل القرض." },
      ],
    },
    lending: {
      eyebrow: "مبنية للإقراض",
      title: "كل محادثة ائتمان، مديرة علاقات واحدة.",
      items: [
        { t: "شخصي", d: "بلا ضمان، بالغرض، والقسط أولًا." },
        { t: "سكني", d: "شراء وبناء وتجديد." },
        { t: "تجاري", d: "رأس مال عامل دون زيارة الفرع." },
        { t: "LAP", d: "قرض مقابل عقار، مشروح بصوت عالٍ." },
        { t: "مركبة", d: "سيارة ودراجة، بما فيها المستعمل." },
        { t: "ذهب", d: "مقابل مجوهرات، والمدة بلغة بسيطة." },
        { t: "نساء", d: "منتجات للمقترضات، بالاسم." },
        { t: "بطاقات", d: "إصدار بطاقة دون اثنتي عشرة صفحة." },
      ],
    },
    why: {
      eyebrow: "صوت لا فروع",
      title: "لماذا الحديث يهزم الطابور.",
      items: [
        { t: "بلا رقم انتظار", d: "مديرة العلاقات على الصفحة. لا تغلق الساعة 4:30." },
        { t: "الأوراق عدو", d: "لا تكتب سبعة عشر حقلًا لتعرف أنك غير مؤهل. تتحدث. هي تملأ." },
        { t: "اللغة هي المنتج", d: "المالايالامية والهندية والتاميلية والإنجليزية والعربية. ليست ترجمة بعد سكربت إنجليزي." },
      ],
    },
    security: {
      eyebrow: "قطاعات منظمة",
      title: "محادثات الائتمان تبقى لك.",
      lede: "تشفير وموافقة وقواعد بيانات تمر بمراجعة الامتثال من اليوم الأول. مكتب ائتمان ناعم فقط عندما يقول المقترض.",
      items: [
        { t: "التشفير", d: "AES-256 في التخزين. TLS 1.3 في النقل." },
        { t: "DPDP", d: "مبنية حول قانون حماية البيانات الشخصية الرقمية في الهند — الغرض والموافقة والحذف." },
        { t: "مكتب ناعم", d: "لا سحب صلب لتصفح الخيارات. المكتب بموافقة ومُسجَّل." },
        { t: "الوصول", d: "أقل صلاحية. أنظمة الإنتاج خلف MFA." },
      ],
    },
    faq: {
      title: "أسئلة شائعة",
      items: [
        {
          q: "ما هي دهانا؟",
          a: "دهانا مديرة علاقات ذكاء اصطناعي للائتمان. المقترضون يتحدثون. ترشدهم عبر المبلغ والغرض والقسط والعروض وKYC على الصفحة. المقرضون شركاء. المنتج PaisaOnClick من Altiora Capital Solution Private Limited.",
        },
        {
          q: "هل أملأ نموذجًا؟",
          a: "لا. تتحدث. دهانا تملأ الطلب أثناء الكلام. إن فضّلت النقر فالحقول موجودة.",
        },
        {
          q: "أي لغات تتحدث؟",
          a: "الإنجليزية والهندية والمالايالامية والتاميلية والعربية. بدّل الملعب في هذه الصفحة لترى المحادثة وهي تُعاد كتابتها.",
        },
        {
          q: "هل الأسعار هنا عروض حقيقية؟",
          a: "لا. بطاقات المقارنة توضيحية. الأهلية والأسعار الحية تأتي من شركاء الإقراض بعد حديثك مع دهانا.",
        },
        {
          q: "كيف تُعالَج بياناتي؟",
          a: "AES-256 وTLS 1.3 وموافقة وفق DPDP ومكتب ناعم بإذن صريح فقط. لا نبيع محادثات المقترضين.",
        },
        {
          q: "من وراء دهانا؟",
          a: "Altiora Capital Solution Private Limited، إرناكولام، كيرالا. CIN U63120KL2025PTC095578. GST 32ABDC2744E1Z7.",
        },
      ],
    },
    close: {
      title: "جاهزة عندما تكون جاهزًا.",
      sub: "تحدث عن القرض كما تتحدث إلى مدير علاقات — ثم اختر.",
      cta: "تحدث إلى دهانا",
    },
    footer: {
      blurb: "دهانا مديرة علاقات الذكاء الاصطناعي للائتمان. منتج من PaisaOnClick.",
      company: "Altiora Capital Solution Private Limited",
      address: "The Office, 4th Floor, Jos Annex, Jos Junction, MG Road, Ernakulam South, Kerala 682016",
      cin: "CIN U63120KL2025PTC095578",
      gst: "GST 32ABDC2744E1Z7",
      product: "المنتج",
      companyLink: "الشركة",
      legal: "قانوني",
    },
    float: "تحدث إلى وكيل دهانا",
  },
};
